// Generated by vsg 01042

module cy7c04314bv_mx_bw(
  clkp1,
  clkp2,
  clkp3,
  clkp4,
  oep1_n,
  oep2_n,
  oep3_n,
  oep4_n,
  r_w_np1,
  r_w_np2,
  r_w_np3,
  r_w_np4,
  ce0p1_n,
  ce0p2_n,
  ce0p3_n,
  ce0p4_n,
  ce1p1,
  ce1p2,
  ce1p3,
  ce1p4,
  intp1_n,
  intp2_n,
  intp3_n,
  intp4_n,
  mrst_n,
  iop1,
  iop2,
  iop3,
  iop4,
  bep1_n,
  bep2_n,
  bep3_n,
  bep4_n,
  ap1,
  ap2,
  ap3,
  ap4 );

  // Allowed timing versions: 
  //  Device Name             TimingVersion
  //  ===========             =============

  // Parameter declarations 
  parameter  ModelType = "SWIFT";
  parameter  DefaultData = "111111111111111111";
  parameter  DelayRange = "Max";
  parameter  MemoryFile = ".";
  parameter  MessageLevel = "15";
  parameter  ModelAlias = ".";
  parameter  ModelConfig = "32'h0";
  parameter  ModelId = "-2";
  parameter  TimingVersion = "133";


  input  clkp1;
  input  clkp2;
  input  clkp3;
  input  clkp4;
  input  oep1_n;
  input  oep2_n;
  input  oep3_n;
  input  oep4_n;
  input  r_w_np1;
  input  r_w_np2;
  input  r_w_np3;
  input  r_w_np4;
  input  ce0p1_n;
  input  ce0p2_n;
  input  ce0p3_n;
  input  ce0p4_n;
  input  ce1p1;
  input  ce1p2;
  input  ce1p3;
  input  ce1p4;
  output intp1_n;
  output intp2_n;
  output intp3_n;
  output intp4_n;
  input  mrst_n;
  inout  [17:0] iop1;
  inout  [17:0] iop2;
  inout  [17:0] iop3;
  inout  [17:0] iop4;
  input  [1:0] bep1_n;
  input  [1:0] bep2_n;
  input  [1:0] bep3_n;
  input  [1:0] bep4_n;
  input  [13:0] ap1;
  input  [13:0] ap2;
  input  [13:0] ap3;
  input  [13:0] ap4;

cy7c04314bv_mx  I1 ( 
  .clkp1(clkp1),
  .clkp2(clkp2),
  .clkp3(clkp3),
  .clkp4(clkp4),
  .oep1_n(oep1_n),
  .oep2_n(oep2_n),
  .oep3_n(oep3_n),
  .oep4_n(oep4_n),
  .r_w_np1(r_w_np1),
  .r_w_np2(r_w_np2),
  .r_w_np3(r_w_np3),
  .r_w_np4(r_w_np4),
  .ce0p1_n(ce0p1_n),
  .ce0p2_n(ce0p2_n),
  .ce0p3_n(ce0p3_n),
  .ce0p4_n(ce0p4_n),
  .ce1p1(ce1p1),
  .ce1p2(ce1p2),
  .ce1p3(ce1p3),
  .ce1p4(ce1p4),
  .intp1_n(intp1_n),
  .intp2_n(intp2_n),
  .intp3_n(intp3_n),
  .intp4_n(intp4_n),
  .mrst_n(mrst_n),
  .iop1_0(iop1[0]),
  .iop1_1(iop1[1]),
  .iop1_2(iop1[2]),
  .iop1_3(iop1[3]),
  .iop1_4(iop1[4]),
  .iop1_5(iop1[5]),
  .iop1_6(iop1[6]),
  .iop1_7(iop1[7]),
  .iop1_8(iop1[8]),
  .iop1_9(iop1[9]),
  .iop1_10(iop1[10]),
  .iop1_11(iop1[11]),
  .iop1_12(iop1[12]),
  .iop1_13(iop1[13]),
  .iop1_14(iop1[14]),
  .iop1_15(iop1[15]),
  .iop1_16(iop1[16]),
  .iop1_17(iop1[17]),
  .iop2_0(iop2[0]),
  .iop2_1(iop2[1]),
  .iop2_2(iop2[2]),
  .iop2_3(iop2[3]),
  .iop2_4(iop2[4]),
  .iop2_5(iop2[5]),
  .iop2_6(iop2[6]),
  .iop2_7(iop2[7]),
  .iop2_8(iop2[8]),
  .iop2_9(iop2[9]),
  .iop2_10(iop2[10]),
  .iop2_11(iop2[11]),
  .iop2_12(iop2[12]),
  .iop2_13(iop2[13]),
  .iop2_14(iop2[14]),
  .iop2_15(iop2[15]),
  .iop2_16(iop2[16]),
  .iop2_17(iop2[17]),
  .iop3_0(iop3[0]),
  .iop3_1(iop3[1]),
  .iop3_2(iop3[2]),
  .iop3_3(iop3[3]),
  .iop3_4(iop3[4]),
  .iop3_5(iop3[5]),
  .iop3_6(iop3[6]),
  .iop3_7(iop3[7]),
  .iop3_8(iop3[8]),
  .iop3_9(iop3[9]),
  .iop3_10(iop3[10]),
  .iop3_11(iop3[11]),
  .iop3_12(iop3[12]),
  .iop3_13(iop3[13]),
  .iop3_14(iop3[14]),
  .iop3_15(iop3[15]),
  .iop3_16(iop3[16]),
  .iop3_17(iop3[17]),
  .iop4_0(iop4[0]),
  .iop4_1(iop4[1]),
  .iop4_2(iop4[2]),
  .iop4_3(iop4[3]),
  .iop4_4(iop4[4]),
  .iop4_5(iop4[5]),
  .iop4_6(iop4[6]),
  .iop4_7(iop4[7]),
  .iop4_8(iop4[8]),
  .iop4_9(iop4[9]),
  .iop4_10(iop4[10]),
  .iop4_11(iop4[11]),
  .iop4_12(iop4[12]),
  .iop4_13(iop4[13]),
  .iop4_14(iop4[14]),
  .iop4_15(iop4[15]),
  .iop4_16(iop4[16]),
  .iop4_17(iop4[17]),
  .bep1_n_0(bep1_n[0]),
  .bep1_n_1(bep1_n[1]),
  .bep2_n_0(bep2_n[0]),
  .bep2_n_1(bep2_n[1]),
  .bep3_n_0(bep3_n[0]),
  .bep3_n_1(bep3_n[1]),
  .bep4_n_0(bep4_n[0]),
  .bep4_n_1(bep4_n[1]),
  .ap1_0(ap1[0]),
  .ap1_1(ap1[1]),
  .ap1_2(ap1[2]),
  .ap1_3(ap1[3]),
  .ap1_4(ap1[4]),
  .ap1_5(ap1[5]),
  .ap1_6(ap1[6]),
  .ap1_7(ap1[7]),
  .ap1_8(ap1[8]),
  .ap1_9(ap1[9]),
  .ap1_10(ap1[10]),
  .ap1_11(ap1[11]),
  .ap1_12(ap1[12]),
  .ap1_13(ap1[13]),
  .ap2_0(ap2[0]),
  .ap2_1(ap2[1]),
  .ap2_2(ap2[2]),
  .ap2_3(ap2[3]),
  .ap2_4(ap2[4]),
  .ap2_5(ap2[5]),
  .ap2_6(ap2[6]),
  .ap2_7(ap2[7]),
  .ap2_8(ap2[8]),
  .ap2_9(ap2[9]),
  .ap2_10(ap2[10]),
  .ap2_11(ap2[11]),
  .ap2_12(ap2[12]),
  .ap2_13(ap2[13]),
  .ap3_0(ap3[0]),
  .ap3_1(ap3[1]),
  .ap3_2(ap3[2]),
  .ap3_3(ap3[3]),
  .ap3_4(ap3[4]),
  .ap3_5(ap3[5]),
  .ap3_6(ap3[6]),
  .ap3_7(ap3[7]),
  .ap3_8(ap3[8]),
  .ap3_9(ap3[9]),
  .ap3_10(ap3[10]),
  .ap3_11(ap3[11]),
  .ap3_12(ap3[12]),
  .ap3_13(ap3[13]),
  .ap4_0(ap4[0]),
  .ap4_1(ap4[1]),
  .ap4_2(ap4[2]),
  .ap4_3(ap4[3]),
  .ap4_4(ap4[4]),
  .ap4_5(ap4[5]),
  .ap4_6(ap4[6]),
  .ap4_7(ap4[7]),
  .ap4_8(ap4[8]),
  .ap4_9(ap4[9]),
  .ap4_10(ap4[10]),
  .ap4_11(ap4[11]),
  .ap4_12(ap4[12]),
  .ap4_13(ap4[13]));
  defparam
    I1.DefaultData = DefaultData,
    I1.DelayRange = DelayRange,
    I1.MemoryFile = MemoryFile,
    I1.MessageLevel = MessageLevel,
    I1.ModelAlias = ModelAlias,
    I1.ModelConfig = ModelConfig,
    I1.ModelId = ModelId,
    I1.TimingVersion = TimingVersion;

endmodule
