// Generated by vsg 01042

`timescale 100ps / 100ps
module cy7c0831v_mx(
  clkl,
  clkr,
  oel_n,
  oer_n,
  r_w_nl,
  r_w_nr,
  ce0l_n,
  ce0r_n,
  ce1l,
  ce1r,
  adsl_n,
  adsr_n,
  cntenl_n,
  cntenr_n,
  cntrstl_n,
  cntrstr_n,
  cnt_msk_nl,
  cnt_msk_nr,
  intl_n,
  intr_n,
  cntintl_n,
  cntintr_n,
  mrst_n,
  bl_n_0,
  bl_n_1,
  br_n_0,
  br_n_1,
  dql_0,
  dql_1,
  dql_2,
  dql_3,
  dql_4,
  dql_5,
  dql_6,
  dql_7,
  dql_8,
  dql_9,
  dql_10,
  dql_11,
  dql_12,
  dql_13,
  dql_14,
  dql_15,
  dql_16,
  dql_17,
  dqr_0,
  dqr_1,
  dqr_2,
  dqr_3,
  dqr_4,
  dqr_5,
  dqr_6,
  dqr_7,
  dqr_8,
  dqr_9,
  dqr_10,
  dqr_11,
  dqr_12,
  dqr_13,
  dqr_14,
  dqr_15,
  dqr_16,
  dqr_17,
  al_0,
  al_1,
  al_2,
  al_3,
  al_4,
  al_5,
  al_6,
  al_7,
  al_8,
  al_9,
  al_10,
  al_11,
  al_12,
  al_13,
  al_14,
  al_15,
  al_16,
  ar_0,
  ar_1,
  ar_2,
  ar_3,
  ar_4,
  ar_5,
  ar_6,
  ar_7,
  ar_8,
  ar_9,
  ar_10,
  ar_11,
  ar_12,
  ar_13,
  ar_14,
  ar_15,
  ar_16 );

  // Pin declarations 
  input  clkl;
  input  clkr;
  input  oel_n;
  input  oer_n;
  input  r_w_nl;
  input  r_w_nr;
  input  ce0l_n;
  input  ce0r_n;
  input  ce1l;
  input  ce1r;
  input  adsl_n;
  input  adsr_n;
  input  cntenl_n;
  input  cntenr_n;
  input  cntrstl_n;
  input  cntrstr_n;
  input  cnt_msk_nl;
  input  cnt_msk_nr;
  output intl_n;
  reg    intl_n__PULL;
  reg    intl_n__STRONG;
  assign (pull0, pull1) intl_n = intl_n__PULL;
  assign intl_n = intl_n__STRONG;
  output intr_n;
  reg    intr_n__PULL;
  reg    intr_n__STRONG;
  assign (pull0, pull1) intr_n = intr_n__PULL;
  assign intr_n = intr_n__STRONG;
  output cntintl_n;
  reg    cntintl_n__PULL;
  reg    cntintl_n__STRONG;
  assign (pull0, pull1) cntintl_n = cntintl_n__PULL;
  assign cntintl_n = cntintl_n__STRONG;
  output cntintr_n;
  reg    cntintr_n__PULL;
  reg    cntintr_n__STRONG;
  assign (pull0, pull1) cntintr_n = cntintr_n__PULL;
  assign cntintr_n = cntintr_n__STRONG;
  input  mrst_n;
  input  bl_n_0;
  input  bl_n_1;
  input  br_n_0;
  input  br_n_1;
  inout  dql_0;
  reg    dql_0__PULL;
  reg    dql_0__STRONG;
  assign (pull0, pull1) dql_0 = dql_0__PULL;
  assign dql_0 = dql_0__STRONG;
  inout  dql_1;
  reg    dql_1__PULL;
  reg    dql_1__STRONG;
  assign (pull0, pull1) dql_1 = dql_1__PULL;
  assign dql_1 = dql_1__STRONG;
  inout  dql_2;
  reg    dql_2__PULL;
  reg    dql_2__STRONG;
  assign (pull0, pull1) dql_2 = dql_2__PULL;
  assign dql_2 = dql_2__STRONG;
  inout  dql_3;
  reg    dql_3__PULL;
  reg    dql_3__STRONG;
  assign (pull0, pull1) dql_3 = dql_3__PULL;
  assign dql_3 = dql_3__STRONG;
  inout  dql_4;
  reg    dql_4__PULL;
  reg    dql_4__STRONG;
  assign (pull0, pull1) dql_4 = dql_4__PULL;
  assign dql_4 = dql_4__STRONG;
  inout  dql_5;
  reg    dql_5__PULL;
  reg    dql_5__STRONG;
  assign (pull0, pull1) dql_5 = dql_5__PULL;
  assign dql_5 = dql_5__STRONG;
  inout  dql_6;
  reg    dql_6__PULL;
  reg    dql_6__STRONG;
  assign (pull0, pull1) dql_6 = dql_6__PULL;
  assign dql_6 = dql_6__STRONG;
  inout  dql_7;
  reg    dql_7__PULL;
  reg    dql_7__STRONG;
  assign (pull0, pull1) dql_7 = dql_7__PULL;
  assign dql_7 = dql_7__STRONG;
  inout  dql_8;
  reg    dql_8__PULL;
  reg    dql_8__STRONG;
  assign (pull0, pull1) dql_8 = dql_8__PULL;
  assign dql_8 = dql_8__STRONG;
  inout  dql_9;
  reg    dql_9__PULL;
  reg    dql_9__STRONG;
  assign (pull0, pull1) dql_9 = dql_9__PULL;
  assign dql_9 = dql_9__STRONG;
  inout  dql_10;
  reg    dql_10__PULL;
  reg    dql_10__STRONG;
  assign (pull0, pull1) dql_10 = dql_10__PULL;
  assign dql_10 = dql_10__STRONG;
  inout  dql_11;
  reg    dql_11__PULL;
  reg    dql_11__STRONG;
  assign (pull0, pull1) dql_11 = dql_11__PULL;
  assign dql_11 = dql_11__STRONG;
  inout  dql_12;
  reg    dql_12__PULL;
  reg    dql_12__STRONG;
  assign (pull0, pull1) dql_12 = dql_12__PULL;
  assign dql_12 = dql_12__STRONG;
  inout  dql_13;
  reg    dql_13__PULL;
  reg    dql_13__STRONG;
  assign (pull0, pull1) dql_13 = dql_13__PULL;
  assign dql_13 = dql_13__STRONG;
  inout  dql_14;
  reg    dql_14__PULL;
  reg    dql_14__STRONG;
  assign (pull0, pull1) dql_14 = dql_14__PULL;
  assign dql_14 = dql_14__STRONG;
  inout  dql_15;
  reg    dql_15__PULL;
  reg    dql_15__STRONG;
  assign (pull0, pull1) dql_15 = dql_15__PULL;
  assign dql_15 = dql_15__STRONG;
  inout  dql_16;
  reg    dql_16__PULL;
  reg    dql_16__STRONG;
  assign (pull0, pull1) dql_16 = dql_16__PULL;
  assign dql_16 = dql_16__STRONG;
  inout  dql_17;
  reg    dql_17__PULL;
  reg    dql_17__STRONG;
  assign (pull0, pull1) dql_17 = dql_17__PULL;
  assign dql_17 = dql_17__STRONG;
  inout  dqr_0;
  reg    dqr_0__PULL;
  reg    dqr_0__STRONG;
  assign (pull0, pull1) dqr_0 = dqr_0__PULL;
  assign dqr_0 = dqr_0__STRONG;
  inout  dqr_1;
  reg    dqr_1__PULL;
  reg    dqr_1__STRONG;
  assign (pull0, pull1) dqr_1 = dqr_1__PULL;
  assign dqr_1 = dqr_1__STRONG;
  inout  dqr_2;
  reg    dqr_2__PULL;
  reg    dqr_2__STRONG;
  assign (pull0, pull1) dqr_2 = dqr_2__PULL;
  assign dqr_2 = dqr_2__STRONG;
  inout  dqr_3;
  reg    dqr_3__PULL;
  reg    dqr_3__STRONG;
  assign (pull0, pull1) dqr_3 = dqr_3__PULL;
  assign dqr_3 = dqr_3__STRONG;
  inout  dqr_4;
  reg    dqr_4__PULL;
  reg    dqr_4__STRONG;
  assign (pull0, pull1) dqr_4 = dqr_4__PULL;
  assign dqr_4 = dqr_4__STRONG;
  inout  dqr_5;
  reg    dqr_5__PULL;
  reg    dqr_5__STRONG;
  assign (pull0, pull1) dqr_5 = dqr_5__PULL;
  assign dqr_5 = dqr_5__STRONG;
  inout  dqr_6;
  reg    dqr_6__PULL;
  reg    dqr_6__STRONG;
  assign (pull0, pull1) dqr_6 = dqr_6__PULL;
  assign dqr_6 = dqr_6__STRONG;
  inout  dqr_7;
  reg    dqr_7__PULL;
  reg    dqr_7__STRONG;
  assign (pull0, pull1) dqr_7 = dqr_7__PULL;
  assign dqr_7 = dqr_7__STRONG;
  inout  dqr_8;
  reg    dqr_8__PULL;
  reg    dqr_8__STRONG;
  assign (pull0, pull1) dqr_8 = dqr_8__PULL;
  assign dqr_8 = dqr_8__STRONG;
  inout  dqr_9;
  reg    dqr_9__PULL;
  reg    dqr_9__STRONG;
  assign (pull0, pull1) dqr_9 = dqr_9__PULL;
  assign dqr_9 = dqr_9__STRONG;
  inout  dqr_10;
  reg    dqr_10__PULL;
  reg    dqr_10__STRONG;
  assign (pull0, pull1) dqr_10 = dqr_10__PULL;
  assign dqr_10 = dqr_10__STRONG;
  inout  dqr_11;
  reg    dqr_11__PULL;
  reg    dqr_11__STRONG;
  assign (pull0, pull1) dqr_11 = dqr_11__PULL;
  assign dqr_11 = dqr_11__STRONG;
  inout  dqr_12;
  reg    dqr_12__PULL;
  reg    dqr_12__STRONG;
  assign (pull0, pull1) dqr_12 = dqr_12__PULL;
  assign dqr_12 = dqr_12__STRONG;
  inout  dqr_13;
  reg    dqr_13__PULL;
  reg    dqr_13__STRONG;
  assign (pull0, pull1) dqr_13 = dqr_13__PULL;
  assign dqr_13 = dqr_13__STRONG;
  inout  dqr_14;
  reg    dqr_14__PULL;
  reg    dqr_14__STRONG;
  assign (pull0, pull1) dqr_14 = dqr_14__PULL;
  assign dqr_14 = dqr_14__STRONG;
  inout  dqr_15;
  reg    dqr_15__PULL;
  reg    dqr_15__STRONG;
  assign (pull0, pull1) dqr_15 = dqr_15__PULL;
  assign dqr_15 = dqr_15__STRONG;
  inout  dqr_16;
  reg    dqr_16__PULL;
  reg    dqr_16__STRONG;
  assign (pull0, pull1) dqr_16 = dqr_16__PULL;
  assign dqr_16 = dqr_16__STRONG;
  inout  dqr_17;
  reg    dqr_17__PULL;
  reg    dqr_17__STRONG;
  assign (pull0, pull1) dqr_17 = dqr_17__PULL;
  assign dqr_17 = dqr_17__STRONG;
  inout  al_0;
  reg    al_0__PULL;
  reg    al_0__STRONG;
  assign (pull0, pull1) al_0 = al_0__PULL;
  assign al_0 = al_0__STRONG;
  inout  al_1;
  reg    al_1__PULL;
  reg    al_1__STRONG;
  assign (pull0, pull1) al_1 = al_1__PULL;
  assign al_1 = al_1__STRONG;
  inout  al_2;
  reg    al_2__PULL;
  reg    al_2__STRONG;
  assign (pull0, pull1) al_2 = al_2__PULL;
  assign al_2 = al_2__STRONG;
  inout  al_3;
  reg    al_3__PULL;
  reg    al_3__STRONG;
  assign (pull0, pull1) al_3 = al_3__PULL;
  assign al_3 = al_3__STRONG;
  inout  al_4;
  reg    al_4__PULL;
  reg    al_4__STRONG;
  assign (pull0, pull1) al_4 = al_4__PULL;
  assign al_4 = al_4__STRONG;
  inout  al_5;
  reg    al_5__PULL;
  reg    al_5__STRONG;
  assign (pull0, pull1) al_5 = al_5__PULL;
  assign al_5 = al_5__STRONG;
  inout  al_6;
  reg    al_6__PULL;
  reg    al_6__STRONG;
  assign (pull0, pull1) al_6 = al_6__PULL;
  assign al_6 = al_6__STRONG;
  inout  al_7;
  reg    al_7__PULL;
  reg    al_7__STRONG;
  assign (pull0, pull1) al_7 = al_7__PULL;
  assign al_7 = al_7__STRONG;
  inout  al_8;
  reg    al_8__PULL;
  reg    al_8__STRONG;
  assign (pull0, pull1) al_8 = al_8__PULL;
  assign al_8 = al_8__STRONG;
  inout  al_9;
  reg    al_9__PULL;
  reg    al_9__STRONG;
  assign (pull0, pull1) al_9 = al_9__PULL;
  assign al_9 = al_9__STRONG;
  inout  al_10;
  reg    al_10__PULL;
  reg    al_10__STRONG;
  assign (pull0, pull1) al_10 = al_10__PULL;
  assign al_10 = al_10__STRONG;
  inout  al_11;
  reg    al_11__PULL;
  reg    al_11__STRONG;
  assign (pull0, pull1) al_11 = al_11__PULL;
  assign al_11 = al_11__STRONG;
  inout  al_12;
  reg    al_12__PULL;
  reg    al_12__STRONG;
  assign (pull0, pull1) al_12 = al_12__PULL;
  assign al_12 = al_12__STRONG;
  inout  al_13;
  reg    al_13__PULL;
  reg    al_13__STRONG;
  assign (pull0, pull1) al_13 = al_13__PULL;
  assign al_13 = al_13__STRONG;
  inout  al_14;
  reg    al_14__PULL;
  reg    al_14__STRONG;
  assign (pull0, pull1) al_14 = al_14__PULL;
  assign al_14 = al_14__STRONG;
  inout  al_15;
  reg    al_15__PULL;
  reg    al_15__STRONG;
  assign (pull0, pull1) al_15 = al_15__PULL;
  assign al_15 = al_15__STRONG;
  inout  al_16;
  reg    al_16__PULL;
  reg    al_16__STRONG;
  assign (pull0, pull1) al_16 = al_16__PULL;
  assign al_16 = al_16__STRONG;
  inout  ar_0;
  reg    ar_0__PULL;
  reg    ar_0__STRONG;
  assign (pull0, pull1) ar_0 = ar_0__PULL;
  assign ar_0 = ar_0__STRONG;
  inout  ar_1;
  reg    ar_1__PULL;
  reg    ar_1__STRONG;
  assign (pull0, pull1) ar_1 = ar_1__PULL;
  assign ar_1 = ar_1__STRONG;
  inout  ar_2;
  reg    ar_2__PULL;
  reg    ar_2__STRONG;
  assign (pull0, pull1) ar_2 = ar_2__PULL;
  assign ar_2 = ar_2__STRONG;
  inout  ar_3;
  reg    ar_3__PULL;
  reg    ar_3__STRONG;
  assign (pull0, pull1) ar_3 = ar_3__PULL;
  assign ar_3 = ar_3__STRONG;
  inout  ar_4;
  reg    ar_4__PULL;
  reg    ar_4__STRONG;
  assign (pull0, pull1) ar_4 = ar_4__PULL;
  assign ar_4 = ar_4__STRONG;
  inout  ar_5;
  reg    ar_5__PULL;
  reg    ar_5__STRONG;
  assign (pull0, pull1) ar_5 = ar_5__PULL;
  assign ar_5 = ar_5__STRONG;
  inout  ar_6;
  reg    ar_6__PULL;
  reg    ar_6__STRONG;
  assign (pull0, pull1) ar_6 = ar_6__PULL;
  assign ar_6 = ar_6__STRONG;
  inout  ar_7;
  reg    ar_7__PULL;
  reg    ar_7__STRONG;
  assign (pull0, pull1) ar_7 = ar_7__PULL;
  assign ar_7 = ar_7__STRONG;
  inout  ar_8;
  reg    ar_8__PULL;
  reg    ar_8__STRONG;
  assign (pull0, pull1) ar_8 = ar_8__PULL;
  assign ar_8 = ar_8__STRONG;
  inout  ar_9;
  reg    ar_9__PULL;
  reg    ar_9__STRONG;
  assign (pull0, pull1) ar_9 = ar_9__PULL;
  assign ar_9 = ar_9__STRONG;
  inout  ar_10;
  reg    ar_10__PULL;
  reg    ar_10__STRONG;
  assign (pull0, pull1) ar_10 = ar_10__PULL;
  assign ar_10 = ar_10__STRONG;
  inout  ar_11;
  reg    ar_11__PULL;
  reg    ar_11__STRONG;
  assign (pull0, pull1) ar_11 = ar_11__PULL;
  assign ar_11 = ar_11__STRONG;
  inout  ar_12;
  reg    ar_12__PULL;
  reg    ar_12__STRONG;
  assign (pull0, pull1) ar_12 = ar_12__PULL;
  assign ar_12 = ar_12__STRONG;
  inout  ar_13;
  reg    ar_13__PULL;
  reg    ar_13__STRONG;
  assign (pull0, pull1) ar_13 = ar_13__PULL;
  assign ar_13 = ar_13__STRONG;
  inout  ar_14;
  reg    ar_14__PULL;
  reg    ar_14__STRONG;
  assign (pull0, pull1) ar_14 = ar_14__PULL;
  assign ar_14 = ar_14__STRONG;
  inout  ar_15;
  reg    ar_15__PULL;
  reg    ar_15__STRONG;
  assign (pull0, pull1) ar_15 = ar_15__PULL;
  assign ar_15 = ar_15__STRONG;
  inout  ar_16;
  reg    ar_16__PULL;
  reg    ar_16__STRONG;
  assign (pull0, pull1) ar_16 = ar_16__PULL;
  assign ar_16 = ar_16__STRONG;

  // Allowed timing versions: 
  //  Device Name             TimingVersion
  //  ===========             =============

  // Parameter declarations 
  parameter  ModelType = "SWIFT";
  parameter  DefaultData = "111111111111111111";
  parameter  DelayRange = "Max";
  parameter  MemoryFile = ".";
  parameter  MessageLevel = "15";
  parameter  ModelAlias = ".";
  parameter  ModelConfig = "32'h0";
  parameter  ModelId = "-2";
  parameter  TimingVersion = "150";

  // Invoke the model 
  initial
    begin
      $lm_model(
        "cy7c0831v_mx_lmtv",
        ModelType,
        "attr", "defaultdata", DefaultData,
        "attr", "delayrange", DelayRange,
        "attr", "memoryfile", MemoryFile,
        "attr", "messagelevel", MessageLevel,
        "attr", "modelalias", ModelAlias,
        "attr", "modelconfig", ModelConfig,
        "attr", "modelid", ModelId,
        "attr", "timingversion", TimingVersion,
        "in", clkl,
        "in", clkr,
        "in", oel_n,
        "in", oer_n,
        "in", r_w_nl,
        "in", r_w_nr,
        "in", ce0l_n,
        "in", ce0r_n,
        "in", ce1l,
        "in", ce1r,
        "in", adsl_n,
        "in", adsr_n,
        "in", cntenl_n,
        "in", cntenr_n,
        "in", cntrstl_n,
        "in", cntrstr_n,
        "in", cnt_msk_nl,
        "in", cnt_msk_nr,
        "out", intl_n, intl_n__STRONG, intl_n__PULL,
        "out", intr_n, intr_n__STRONG, intr_n__PULL,
        "out", cntintl_n, cntintl_n__STRONG, cntintl_n__PULL,
        "out", cntintr_n, cntintr_n__STRONG, cntintr_n__PULL,
        "in", mrst_n,
        "in", bl_n_0,
        "in", bl_n_1,
        "in", br_n_0,
        "in", br_n_1,
        "io", dql_0, dql_0__STRONG, dql_0__PULL,
        "io", dql_1, dql_1__STRONG, dql_1__PULL,
        "io", dql_2, dql_2__STRONG, dql_2__PULL,
        "io", dql_3, dql_3__STRONG, dql_3__PULL,
        "io", dql_4, dql_4__STRONG, dql_4__PULL,
        "io", dql_5, dql_5__STRONG, dql_5__PULL,
        "io", dql_6, dql_6__STRONG, dql_6__PULL,
        "io", dql_7, dql_7__STRONG, dql_7__PULL,
        "io", dql_8, dql_8__STRONG, dql_8__PULL,
        "io", dql_9, dql_9__STRONG, dql_9__PULL,
        "io", dql_10, dql_10__STRONG, dql_10__PULL,
        "io", dql_11, dql_11__STRONG, dql_11__PULL,
        "io", dql_12, dql_12__STRONG, dql_12__PULL,
        "io", dql_13, dql_13__STRONG, dql_13__PULL,
        "io", dql_14, dql_14__STRONG, dql_14__PULL,
        "io", dql_15, dql_15__STRONG, dql_15__PULL,
        "io", dql_16, dql_16__STRONG, dql_16__PULL,
        "io", dql_17, dql_17__STRONG, dql_17__PULL,
        "io", dqr_0, dqr_0__STRONG, dqr_0__PULL,
        "io", dqr_1, dqr_1__STRONG, dqr_1__PULL,
        "io", dqr_2, dqr_2__STRONG, dqr_2__PULL,
        "io", dqr_3, dqr_3__STRONG, dqr_3__PULL,
        "io", dqr_4, dqr_4__STRONG, dqr_4__PULL,
        "io", dqr_5, dqr_5__STRONG, dqr_5__PULL,
        "io", dqr_6, dqr_6__STRONG, dqr_6__PULL,
        "io", dqr_7, dqr_7__STRONG, dqr_7__PULL,
        "io", dqr_8, dqr_8__STRONG, dqr_8__PULL,
        "io", dqr_9, dqr_9__STRONG, dqr_9__PULL,
        "io", dqr_10, dqr_10__STRONG, dqr_10__PULL,
        "io", dqr_11, dqr_11__STRONG, dqr_11__PULL,
        "io", dqr_12, dqr_12__STRONG, dqr_12__PULL,
        "io", dqr_13, dqr_13__STRONG, dqr_13__PULL,
        "io", dqr_14, dqr_14__STRONG, dqr_14__PULL,
        "io", dqr_15, dqr_15__STRONG, dqr_15__PULL,
        "io", dqr_16, dqr_16__STRONG, dqr_16__PULL,
        "io", dqr_17, dqr_17__STRONG, dqr_17__PULL,
        "io", al_0, al_0__STRONG, al_0__PULL,
        "io", al_1, al_1__STRONG, al_1__PULL,
        "io", al_2, al_2__STRONG, al_2__PULL,
        "io", al_3, al_3__STRONG, al_3__PULL,
        "io", al_4, al_4__STRONG, al_4__PULL,
        "io", al_5, al_5__STRONG, al_5__PULL,
        "io", al_6, al_6__STRONG, al_6__PULL,
        "io", al_7, al_7__STRONG, al_7__PULL,
        "io", al_8, al_8__STRONG, al_8__PULL,
        "io", al_9, al_9__STRONG, al_9__PULL,
        "io", al_10, al_10__STRONG, al_10__PULL,
        "io", al_11, al_11__STRONG, al_11__PULL,
        "io", al_12, al_12__STRONG, al_12__PULL,
        "io", al_13, al_13__STRONG, al_13__PULL,
        "io", al_14, al_14__STRONG, al_14__PULL,
        "io", al_15, al_15__STRONG, al_15__PULL,
        "io", al_16, al_16__STRONG, al_16__PULL,
        "io", ar_0, ar_0__STRONG, ar_0__PULL,
        "io", ar_1, ar_1__STRONG, ar_1__PULL,
        "io", ar_2, ar_2__STRONG, ar_2__PULL,
        "io", ar_3, ar_3__STRONG, ar_3__PULL,
        "io", ar_4, ar_4__STRONG, ar_4__PULL,
        "io", ar_5, ar_5__STRONG, ar_5__PULL,
        "io", ar_6, ar_6__STRONG, ar_6__PULL,
        "io", ar_7, ar_7__STRONG, ar_7__PULL,
        "io", ar_8, ar_8__STRONG, ar_8__PULL,
        "io", ar_9, ar_9__STRONG, ar_9__PULL,
        "io", ar_10, ar_10__STRONG, ar_10__PULL,
        "io", ar_11, ar_11__STRONG, ar_11__PULL,
        "io", ar_12, ar_12__STRONG, ar_12__PULL,
        "io", ar_13, ar_13__STRONG, ar_13__PULL,
        "io", ar_14, ar_14__STRONG, ar_14__PULL,
        "io", ar_15, ar_15__STRONG, ar_15__PULL,
        "io", ar_16, ar_16__STRONG, ar_16__PULL );
    end

endmodule
