// Generated by vsg 01042

`timescale 100ps / 100ps
module hy57v161610d_a_mx(
  ba,
  dq__SWIFT_BUS__0,
  dq__SWIFT_BUS__1,
  dq__SWIFT_BUS__2,
  dq__SWIFT_BUS__3,
  dq__SWIFT_BUS__4,
  dq__SWIFT_BUS__5,
  dq__SWIFT_BUS__6,
  dq__SWIFT_BUS__7,
  dq__SWIFT_BUS__8,
  dq__SWIFT_BUS__9,
  dq__SWIFT_BUS__10,
  dq__SWIFT_BUS__11,
  dq__SWIFT_BUS__12,
  dq__SWIFT_BUS__13,
  dq__SWIFT_BUS__14,
  dq__SWIFT_BUS__15,
  we_n,
  cas_n,
  ras_n,
  cs_n,
  a__SWIFT_BUS__0,
  a__SWIFT_BUS__1,
  a__SWIFT_BUS__2,
  a__SWIFT_BUS__3,
  a__SWIFT_BUS__4,
  a__SWIFT_BUS__5,
  a__SWIFT_BUS__6,
  a__SWIFT_BUS__7,
  a__SWIFT_BUS__8,
  a__SWIFT_BUS__9,
  a__SWIFT_BUS__10,
  cke,
  dqm__SWIFT_BUS__0,
  dqm__SWIFT_BUS__1,
  clk );

  // Pin declarations 
  input  ba;
  inout  dq__SWIFT_BUS__0;
  reg    dq__SWIFT_BUS__0__PULL;
  reg    dq__SWIFT_BUS__0__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__0 = dq__SWIFT_BUS__0__PULL;
  assign dq__SWIFT_BUS__0 = dq__SWIFT_BUS__0__STRONG;
  inout  dq__SWIFT_BUS__1;
  reg    dq__SWIFT_BUS__1__PULL;
  reg    dq__SWIFT_BUS__1__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__1 = dq__SWIFT_BUS__1__PULL;
  assign dq__SWIFT_BUS__1 = dq__SWIFT_BUS__1__STRONG;
  inout  dq__SWIFT_BUS__2;
  reg    dq__SWIFT_BUS__2__PULL;
  reg    dq__SWIFT_BUS__2__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__2 = dq__SWIFT_BUS__2__PULL;
  assign dq__SWIFT_BUS__2 = dq__SWIFT_BUS__2__STRONG;
  inout  dq__SWIFT_BUS__3;
  reg    dq__SWIFT_BUS__3__PULL;
  reg    dq__SWIFT_BUS__3__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__3 = dq__SWIFT_BUS__3__PULL;
  assign dq__SWIFT_BUS__3 = dq__SWIFT_BUS__3__STRONG;
  inout  dq__SWIFT_BUS__4;
  reg    dq__SWIFT_BUS__4__PULL;
  reg    dq__SWIFT_BUS__4__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__4 = dq__SWIFT_BUS__4__PULL;
  assign dq__SWIFT_BUS__4 = dq__SWIFT_BUS__4__STRONG;
  inout  dq__SWIFT_BUS__5;
  reg    dq__SWIFT_BUS__5__PULL;
  reg    dq__SWIFT_BUS__5__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__5 = dq__SWIFT_BUS__5__PULL;
  assign dq__SWIFT_BUS__5 = dq__SWIFT_BUS__5__STRONG;
  inout  dq__SWIFT_BUS__6;
  reg    dq__SWIFT_BUS__6__PULL;
  reg    dq__SWIFT_BUS__6__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__6 = dq__SWIFT_BUS__6__PULL;
  assign dq__SWIFT_BUS__6 = dq__SWIFT_BUS__6__STRONG;
  inout  dq__SWIFT_BUS__7;
  reg    dq__SWIFT_BUS__7__PULL;
  reg    dq__SWIFT_BUS__7__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__7 = dq__SWIFT_BUS__7__PULL;
  assign dq__SWIFT_BUS__7 = dq__SWIFT_BUS__7__STRONG;
  inout  dq__SWIFT_BUS__8;
  reg    dq__SWIFT_BUS__8__PULL;
  reg    dq__SWIFT_BUS__8__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__8 = dq__SWIFT_BUS__8__PULL;
  assign dq__SWIFT_BUS__8 = dq__SWIFT_BUS__8__STRONG;
  inout  dq__SWIFT_BUS__9;
  reg    dq__SWIFT_BUS__9__PULL;
  reg    dq__SWIFT_BUS__9__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__9 = dq__SWIFT_BUS__9__PULL;
  assign dq__SWIFT_BUS__9 = dq__SWIFT_BUS__9__STRONG;
  inout  dq__SWIFT_BUS__10;
  reg    dq__SWIFT_BUS__10__PULL;
  reg    dq__SWIFT_BUS__10__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__10 = dq__SWIFT_BUS__10__PULL;
  assign dq__SWIFT_BUS__10 = dq__SWIFT_BUS__10__STRONG;
  inout  dq__SWIFT_BUS__11;
  reg    dq__SWIFT_BUS__11__PULL;
  reg    dq__SWIFT_BUS__11__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__11 = dq__SWIFT_BUS__11__PULL;
  assign dq__SWIFT_BUS__11 = dq__SWIFT_BUS__11__STRONG;
  inout  dq__SWIFT_BUS__12;
  reg    dq__SWIFT_BUS__12__PULL;
  reg    dq__SWIFT_BUS__12__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__12 = dq__SWIFT_BUS__12__PULL;
  assign dq__SWIFT_BUS__12 = dq__SWIFT_BUS__12__STRONG;
  inout  dq__SWIFT_BUS__13;
  reg    dq__SWIFT_BUS__13__PULL;
  reg    dq__SWIFT_BUS__13__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__13 = dq__SWIFT_BUS__13__PULL;
  assign dq__SWIFT_BUS__13 = dq__SWIFT_BUS__13__STRONG;
  inout  dq__SWIFT_BUS__14;
  reg    dq__SWIFT_BUS__14__PULL;
  reg    dq__SWIFT_BUS__14__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__14 = dq__SWIFT_BUS__14__PULL;
  assign dq__SWIFT_BUS__14 = dq__SWIFT_BUS__14__STRONG;
  inout  dq__SWIFT_BUS__15;
  reg    dq__SWIFT_BUS__15__PULL;
  reg    dq__SWIFT_BUS__15__STRONG;
  assign (pull0, pull1) dq__SWIFT_BUS__15 = dq__SWIFT_BUS__15__PULL;
  assign dq__SWIFT_BUS__15 = dq__SWIFT_BUS__15__STRONG;
  input  we_n;
  input  cas_n;
  input  ras_n;
  input  cs_n;
  input  a__SWIFT_BUS__0;
  input  a__SWIFT_BUS__1;
  input  a__SWIFT_BUS__2;
  input  a__SWIFT_BUS__3;
  input  a__SWIFT_BUS__4;
  input  a__SWIFT_BUS__5;
  input  a__SWIFT_BUS__6;
  input  a__SWIFT_BUS__7;
  input  a__SWIFT_BUS__8;
  input  a__SWIFT_BUS__9;
  input  a__SWIFT_BUS__10;
  input  cke;
  input  dqm__SWIFT_BUS__0;
  input  dqm__SWIFT_BUS__1;
  input  clk;

  // Allowed timing versions: 
  //  Device Name             TimingVersion
  //  ===========             =============

  // Parameter declarations 
  parameter  ModelType = "SWIFT";
  parameter  DefaultData = "1111111111111111";
  parameter  DelayRange = "Max";
  parameter  MemoryFile = ".";
  parameter  MessageLevel = "15";
  parameter  ModelAlias = ".";
  parameter  ModelConfig = "32'h0";
  parameter  ModelId = "-2";
  parameter  TimingVersion = "5";

  // Invoke the model 
  initial
    begin
      $lm_model(
        "hy57v161610d_a_mx_lmtv",
        ModelType,
        "attr", "defaultdata", DefaultData,
        "attr", "delayrange", DelayRange,
        "attr", "memoryfile", MemoryFile,
        "attr", "messagelevel", MessageLevel,
        "attr", "modelalias", ModelAlias,
        "attr", "modelconfig", ModelConfig,
        "attr", "modelid", ModelId,
        "attr", "timingversion", TimingVersion,
        "in", ba,
        "io", dq__SWIFT_BUS__0, dq__SWIFT_BUS__0__STRONG, dq__SWIFT_BUS__0__PULL,
        "io", dq__SWIFT_BUS__1, dq__SWIFT_BUS__1__STRONG, dq__SWIFT_BUS__1__PULL,
        "io", dq__SWIFT_BUS__2, dq__SWIFT_BUS__2__STRONG, dq__SWIFT_BUS__2__PULL,
        "io", dq__SWIFT_BUS__3, dq__SWIFT_BUS__3__STRONG, dq__SWIFT_BUS__3__PULL,
        "io", dq__SWIFT_BUS__4, dq__SWIFT_BUS__4__STRONG, dq__SWIFT_BUS__4__PULL,
        "io", dq__SWIFT_BUS__5, dq__SWIFT_BUS__5__STRONG, dq__SWIFT_BUS__5__PULL,
        "io", dq__SWIFT_BUS__6, dq__SWIFT_BUS__6__STRONG, dq__SWIFT_BUS__6__PULL,
        "io", dq__SWIFT_BUS__7, dq__SWIFT_BUS__7__STRONG, dq__SWIFT_BUS__7__PULL,
        "io", dq__SWIFT_BUS__8, dq__SWIFT_BUS__8__STRONG, dq__SWIFT_BUS__8__PULL,
        "io", dq__SWIFT_BUS__9, dq__SWIFT_BUS__9__STRONG, dq__SWIFT_BUS__9__PULL,
        "io", dq__SWIFT_BUS__10, dq__SWIFT_BUS__10__STRONG, dq__SWIFT_BUS__10__PULL,
        "io", dq__SWIFT_BUS__11, dq__SWIFT_BUS__11__STRONG, dq__SWIFT_BUS__11__PULL,
        "io", dq__SWIFT_BUS__12, dq__SWIFT_BUS__12__STRONG, dq__SWIFT_BUS__12__PULL,
        "io", dq__SWIFT_BUS__13, dq__SWIFT_BUS__13__STRONG, dq__SWIFT_BUS__13__PULL,
        "io", dq__SWIFT_BUS__14, dq__SWIFT_BUS__14__STRONG, dq__SWIFT_BUS__14__PULL,
        "io", dq__SWIFT_BUS__15, dq__SWIFT_BUS__15__STRONG, dq__SWIFT_BUS__15__PULL,
        "in", we_n,
        "in", cas_n,
        "in", ras_n,
        "in", cs_n,
        "in", a__SWIFT_BUS__0,
        "in", a__SWIFT_BUS__1,
        "in", a__SWIFT_BUS__2,
        "in", a__SWIFT_BUS__3,
        "in", a__SWIFT_BUS__4,
        "in", a__SWIFT_BUS__5,
        "in", a__SWIFT_BUS__6,
        "in", a__SWIFT_BUS__7,
        "in", a__SWIFT_BUS__8,
        "in", a__SWIFT_BUS__9,
        "in", a__SWIFT_BUS__10,
        "in", cke,
        "in", dqm__SWIFT_BUS__0,
        "in", dqm__SWIFT_BUS__1,
        "in", clk );
    end

endmodule
