// Generated by vsg 01042

module hy57v161610d_a_mx_bw(
  ba,
  dq,
  we_n,
  cas_n,
  ras_n,
  cs_n,
  a,
  cke,
  dqm,
  clk );

  // Allowed timing versions: 
  //  Device Name             TimingVersion
  //  ===========             =============

  // Parameter declarations 
  parameter  ModelType = "SWIFT";
  parameter  DefaultData = "1111111111111111";
  parameter  DelayRange = "Max";
  parameter  MemoryFile = ".";
  parameter  MessageLevel = "15";
  parameter  ModelAlias = ".";
  parameter  ModelConfig = "32'h0";
  parameter  ModelId = "-2";
  parameter  TimingVersion = "5";


  input  ba;
  inout  [15:0] dq;
  input  we_n;
  input  cas_n;
  input  ras_n;
  input  cs_n;
  input  [10:0] a;
  input  cke;
  input  [1:0] dqm;
  input  clk;

hy57v161610d_a_mx  I1 ( 
  .ba(ba),
  .dq__SWIFT_BUS__0(dq[0]),
  .dq__SWIFT_BUS__1(dq[1]),
  .dq__SWIFT_BUS__2(dq[2]),
  .dq__SWIFT_BUS__3(dq[3]),
  .dq__SWIFT_BUS__4(dq[4]),
  .dq__SWIFT_BUS__5(dq[5]),
  .dq__SWIFT_BUS__6(dq[6]),
  .dq__SWIFT_BUS__7(dq[7]),
  .dq__SWIFT_BUS__8(dq[8]),
  .dq__SWIFT_BUS__9(dq[9]),
  .dq__SWIFT_BUS__10(dq[10]),
  .dq__SWIFT_BUS__11(dq[11]),
  .dq__SWIFT_BUS__12(dq[12]),
  .dq__SWIFT_BUS__13(dq[13]),
  .dq__SWIFT_BUS__14(dq[14]),
  .dq__SWIFT_BUS__15(dq[15]),
  .we_n(we_n),
  .cas_n(cas_n),
  .ras_n(ras_n),
  .cs_n(cs_n),
  .a__SWIFT_BUS__0(a[0]),
  .a__SWIFT_BUS__1(a[1]),
  .a__SWIFT_BUS__2(a[2]),
  .a__SWIFT_BUS__3(a[3]),
  .a__SWIFT_BUS__4(a[4]),
  .a__SWIFT_BUS__5(a[5]),
  .a__SWIFT_BUS__6(a[6]),
  .a__SWIFT_BUS__7(a[7]),
  .a__SWIFT_BUS__8(a[8]),
  .a__SWIFT_BUS__9(a[9]),
  .a__SWIFT_BUS__10(a[10]),
  .cke(cke),
  .dqm__SWIFT_BUS__0(dqm[0]),
  .dqm__SWIFT_BUS__1(dqm[1]),
  .clk(clk));
  defparam
    I1.DefaultData = DefaultData,
    I1.DelayRange = DelayRange,
    I1.MemoryFile = MemoryFile,
    I1.MessageLevel = MessageLevel,
    I1.ModelAlias = ModelAlias,
    I1.ModelConfig = ModelConfig,
    I1.ModelId = ModelId,
    I1.TimingVersion = TimingVersion;

endmodule
