// Generated by vsg 01042

`timescale 100ps / 100ps
module km68257c_mx(
  io__SWIFT_BUS__1,
  io__SWIFT_BUS__2,
  io__SWIFT_BUS__3,
  io__SWIFT_BUS__4,
  io__SWIFT_BUS__5,
  io__SWIFT_BUS__6,
  io__SWIFT_BUS__7,
  io__SWIFT_BUS__8,
  we_n,
  cs_n,
  oe_n,
  a__SWIFT_BUS__0,
  a__SWIFT_BUS__1,
  a__SWIFT_BUS__2,
  a__SWIFT_BUS__3,
  a__SWIFT_BUS__4,
  a__SWIFT_BUS__5,
  a__SWIFT_BUS__6,
  a__SWIFT_BUS__7,
  a__SWIFT_BUS__8,
  a__SWIFT_BUS__9,
  a__SWIFT_BUS__10,
  a__SWIFT_BUS__11,
  a__SWIFT_BUS__12,
  a__SWIFT_BUS__13,
  a__SWIFT_BUS__14 );

  // Pin declarations 
  inout  io__SWIFT_BUS__1;
  reg    io__SWIFT_BUS__1__PULL;
  reg    io__SWIFT_BUS__1__STRONG;
  assign (pull0, pull1) io__SWIFT_BUS__1 = io__SWIFT_BUS__1__PULL;
  assign io__SWIFT_BUS__1 = io__SWIFT_BUS__1__STRONG;
  inout  io__SWIFT_BUS__2;
  reg    io__SWIFT_BUS__2__PULL;
  reg    io__SWIFT_BUS__2__STRONG;
  assign (pull0, pull1) io__SWIFT_BUS__2 = io__SWIFT_BUS__2__PULL;
  assign io__SWIFT_BUS__2 = io__SWIFT_BUS__2__STRONG;
  inout  io__SWIFT_BUS__3;
  reg    io__SWIFT_BUS__3__PULL;
  reg    io__SWIFT_BUS__3__STRONG;
  assign (pull0, pull1) io__SWIFT_BUS__3 = io__SWIFT_BUS__3__PULL;
  assign io__SWIFT_BUS__3 = io__SWIFT_BUS__3__STRONG;
  inout  io__SWIFT_BUS__4;
  reg    io__SWIFT_BUS__4__PULL;
  reg    io__SWIFT_BUS__4__STRONG;
  assign (pull0, pull1) io__SWIFT_BUS__4 = io__SWIFT_BUS__4__PULL;
  assign io__SWIFT_BUS__4 = io__SWIFT_BUS__4__STRONG;
  inout  io__SWIFT_BUS__5;
  reg    io__SWIFT_BUS__5__PULL;
  reg    io__SWIFT_BUS__5__STRONG;
  assign (pull0, pull1) io__SWIFT_BUS__5 = io__SWIFT_BUS__5__PULL;
  assign io__SWIFT_BUS__5 = io__SWIFT_BUS__5__STRONG;
  inout  io__SWIFT_BUS__6;
  reg    io__SWIFT_BUS__6__PULL;
  reg    io__SWIFT_BUS__6__STRONG;
  assign (pull0, pull1) io__SWIFT_BUS__6 = io__SWIFT_BUS__6__PULL;
  assign io__SWIFT_BUS__6 = io__SWIFT_BUS__6__STRONG;
  inout  io__SWIFT_BUS__7;
  reg    io__SWIFT_BUS__7__PULL;
  reg    io__SWIFT_BUS__7__STRONG;
  assign (pull0, pull1) io__SWIFT_BUS__7 = io__SWIFT_BUS__7__PULL;
  assign io__SWIFT_BUS__7 = io__SWIFT_BUS__7__STRONG;
  inout  io__SWIFT_BUS__8;
  reg    io__SWIFT_BUS__8__PULL;
  reg    io__SWIFT_BUS__8__STRONG;
  assign (pull0, pull1) io__SWIFT_BUS__8 = io__SWIFT_BUS__8__PULL;
  assign io__SWIFT_BUS__8 = io__SWIFT_BUS__8__STRONG;
  input  we_n;
  input  cs_n;
  input  oe_n;
  input  a__SWIFT_BUS__0;
  input  a__SWIFT_BUS__1;
  input  a__SWIFT_BUS__2;
  input  a__SWIFT_BUS__3;
  input  a__SWIFT_BUS__4;
  input  a__SWIFT_BUS__5;
  input  a__SWIFT_BUS__6;
  input  a__SWIFT_BUS__7;
  input  a__SWIFT_BUS__8;
  input  a__SWIFT_BUS__9;
  input  a__SWIFT_BUS__10;
  input  a__SWIFT_BUS__11;
  input  a__SWIFT_BUS__12;
  input  a__SWIFT_BUS__13;
  input  a__SWIFT_BUS__14;

  // Allowed timing versions: 
  //  Device Name             TimingVersion
  //  ===========             =============

  // Parameter declarations 
  parameter  ModelType = "SWIFT";
  parameter  DefaultData = "11111111";
  parameter  DelayRange = "Max";
  parameter  MemoryFile = ".";
  parameter  MessageLevel = "15";
  parameter  ModelAlias = ".";
  parameter  ModelConfig = "32'h0";
  parameter  ModelId = "-2";
  parameter  TimingVersion = "12";

  // Invoke the model 
  initial
    begin
      $lm_model(
        "km68257c_mx_lmtv",
        ModelType,
        "attr", "defaultdata", DefaultData,
        "attr", "delayrange", DelayRange,
        "attr", "memoryfile", MemoryFile,
        "attr", "messagelevel", MessageLevel,
        "attr", "modelalias", ModelAlias,
        "attr", "modelconfig", ModelConfig,
        "attr", "modelid", ModelId,
        "attr", "timingversion", TimingVersion,
        "io", io__SWIFT_BUS__1, io__SWIFT_BUS__1__STRONG, io__SWIFT_BUS__1__PULL,
        "io", io__SWIFT_BUS__2, io__SWIFT_BUS__2__STRONG, io__SWIFT_BUS__2__PULL,
        "io", io__SWIFT_BUS__3, io__SWIFT_BUS__3__STRONG, io__SWIFT_BUS__3__PULL,
        "io", io__SWIFT_BUS__4, io__SWIFT_BUS__4__STRONG, io__SWIFT_BUS__4__PULL,
        "io", io__SWIFT_BUS__5, io__SWIFT_BUS__5__STRONG, io__SWIFT_BUS__5__PULL,
        "io", io__SWIFT_BUS__6, io__SWIFT_BUS__6__STRONG, io__SWIFT_BUS__6__PULL,
        "io", io__SWIFT_BUS__7, io__SWIFT_BUS__7__STRONG, io__SWIFT_BUS__7__PULL,
        "io", io__SWIFT_BUS__8, io__SWIFT_BUS__8__STRONG, io__SWIFT_BUS__8__PULL,
        "in", we_n,
        "in", cs_n,
        "in", oe_n,
        "in", a__SWIFT_BUS__0,
        "in", a__SWIFT_BUS__1,
        "in", a__SWIFT_BUS__2,
        "in", a__SWIFT_BUS__3,
        "in", a__SWIFT_BUS__4,
        "in", a__SWIFT_BUS__5,
        "in", a__SWIFT_BUS__6,
        "in", a__SWIFT_BUS__7,
        "in", a__SWIFT_BUS__8,
        "in", a__SWIFT_BUS__9,
        "in", a__SWIFT_BUS__10,
        "in", a__SWIFT_BUS__11,
        "in", a__SWIFT_BUS__12,
        "in", a__SWIFT_BUS__13,
        "in", a__SWIFT_BUS__14 );
    end

endmodule
