.output sql_out.txt 
create table text(sentence varchar(100),question varchar(100),sql varchar(100), separator varchar(100),number int);
create table results(comp_id int, winner varchar(20), medal varchar(10));
create table athletes(name varchar(20) primary key,  nationality varchar(20), gender char(1));
create table competitions(comp_id int primary key, name varchar(20), type varchar(10));
insert into text values ('Answer to question 1 is','','','--------------------------------------------------------------------------------------------',1);
insert into text values ('Answer to question 2 is','','','--------------------------------------------------------------------------------------------',2);
insert into text values ('Answer to question 3 is','','','--------------------------------------------------------------------------------------------',3);
insert into text values ('Answer to question 4 is','','','--------------------------------------------------------------------------------------------',4);
insert into text values ('Answer to question 5 is','','','--------------------------------------------------------------------------------------------',5);
insert into text values ('Answer to question 6 is','','','--------------------------------------------------------------------------------------------',6);
insert into text values ('Answer to question 7 is','','','--------------------------------------------------------------------------------------------',7);
insert into text values ('Answer to question 8 is','','','--------------------------------------------------------------------------------------------',8);
insert into text values ('Answer to question 9 is','','','--------------------------------------------------------------------------------------------',9);
insert into text values ('Answer to question 10 is','','','--------------------------------------------------------------------------------------------',10);
insert into text values ('Answer to question 11 is','','','--------------------------------------------------------------------------------------------',11);
insert into text values ('Answer to question 12 is','','','--------------------------------------------------------------------------------------------',12);
insert into text values ('Answer to question 13 is','','','--------------------------------------------------------------------------------------------',13);
insert into text values ('Answer to question 14 is','','','--------------------------------------------------------------------------------------------',14);
insert into text values ('Answer to question 15 is','','','--------------------------------------------------------------------------------------------',15);
insert into text values ('Answer to question 16 is','','','--------------------------------------------------------------------------------------------',16);
insert into text values ('Answer to question 17 is','','','--------------------------------------------------------------------------------------------',17);
insert into text values ('Answer to question 18 is','','','--------------------------------------------------------------------------------------------',18);
insert into text values ('Answer to question 19 is','','','--------------------------------------------------------------------------------------------',19);
insert into text values ('Answer to question 20 is','','','--------------------------------------------------------------------------------------------',20);
insert into text values ('Answer to question 21 is','','','--------------------------------------------------------------------------------------------',21);
insert into text values ('Answer to question 22 is','','','--------------------------------------------------------------------------------------------',22);
insert into text values ('Answer to question 23 is','','','--------------------------------------------------------------------------------------------',23);
insert into text values ('Answer to question 24 is','','','--------------------------------------------------------------------------------------------',24);
insert into text values ('Answer to question 25 is','','','--------------------------------------------------------------------------------------------',25);
insert into text values ('Answer to question 26 is','','','--------------------------------------------------------------------------------------------',26);
insert into text values ('Answer to question 27 is','','','--------------------------------------------------------------------------------------------',27);
insert into text values ('Answer to question 28 is','','','--------------------------------------------------------------------------------------------',28);
insert into text values ('Answer to question 29 is','','','--------------------------------------------------------------------------------------------',29);
insert into text values ('Answer to question 30 is','','','--------------------------------------------------------------------------------------------',30);
insert into text values ('Answer to question 31 is','','','--------------------------------------------------------------------------------------------',31);
insert into text values ('Answer to question 32 is','','','--------------------------------------------------------------------------------------------',32);
insert into text values ('Answer to question 33 is','','','--------------------------------------------------------------------------------------------',33);
insert into text values ('Answer to question 34 is','','','--------------------------------------------------------------------------------------------',34);
insert into text values ('Answer to question 35 is','','','--------------------------------------------------------------------------------------------',35);
insert into text values ('Answer to question 36 is','','','--------------------------------------------------------------------------------------------',36);
insert into text values ('Answer to question 37 is','','','--------------------------------------------------------------------------------------------',37);
insert into text values ('Answer to question 38 is','','','--------------------------------------------------------------------------------------------',38);
insert into text values ('Answer to question 39 is','','','--------------------------------------------------------------------------------------------',39);
insert into text values ('Answer to question 40 is','','','--------------------------------------------------------------------------------------------',40);
insert into text values ('Answer to question 41 is','','','--------------------------------------------------------------------------------------------',41);
insert into text values ('Answer to question 42 is','','','--------------------------------------------------------------------------------------------',42);
insert into text values ('Answer to question 43 is','','','--------------------------------------------------------------------------------------------',43);
insert into text values ('Answer to question 44 is','','','--------------------------------------------------------------------------------------------',44);
insert into text values ('Answer to question 45 is','','','--------------------------------------------------------------------------------------------',45);
insert into text values ('Answer to question 46 is','','','--------------------------------------------------------------------------------------------',46);
insert into text values ('Answer to question 47 is','','','--------------------------------------------------------------------------------------------',47);
insert into text values ('Answer to question 48 is','','','--------------------------------------------------------------------------------------------',48);
insert into text values ('Answer to question 49 is','','','--------------------------------------------------------------------------------------------',49);
insert into text values ('Answer to question 50 is','','','--------------------------------------------------------------------------------------------',50);
insert into text values ('Answer to question 51 is','','','--------------------------------------------------------------------------------------------',51);
insert into text values ('Answer to question 52 is','','','--------------------------------------------------------------------------------------------',53);
insert into text values ('Answer to question 54 is','','','--------------------------------------------------------------------------------------------',54);
insert into text values ('Answer to question 55 is','','','--------------------------------------------------------------------------------------------',55);
insert into text values ('Answer to question 56 is','','','--------------------------------------------------------------------------------------------',56);
insert into text values ('Answer to question 57 is','','','--------------------------------------------------------------------------------------------',57);
insert into text values ('Answer to question 58 is','','','--------------------------------------------------------------------------------------------',58);
insert into results values (3, 'svendsen','silver');
insert into results values(3, 'jay','gold');
insert into results values(3, 'fak','bronze');
insert into results values(4,'ammann','gold');
insert into results values(4,'malysz','silver');
insert into results values(4,'schlierenzauer','bronze');
insert into results values(5,'davis','gold');
insert into results values(5,'mo','silver');
insert into results values(5,'hedrick','bronze');
insert into results values(6,'kramer','gold');
insert into results values(6,'lee','silver');
insert into results values(6,'skobrev','bronze');
insert into results values(7,'ohno','silver');
insert into results values(7,'lee','gold');
insert into results values(7,'cleski','bronze');
insert into results values(9,'kim','gold');
insert into results values(9,'rochette','bronze');
insert into results values(9,'asada','silver');
insert into results values(9,'lysacek','gold');
insert into results values(9,'plushenko','silver');
insert into results values(9,'takahashi','bronze');
insert into results values(10,'miller','gold');
insert into results values(10,'kostelic','silver');
insert into results values(10,'zurbriggen','bronze');
insert into results values(11,'mcivor','gold');
insert into results values(11,'hedda','silver');
insert into results values(11,'huttary','bronze');
insert into results values(12,'razzoli','gold');
insert into results values(12,'kostelic','silver');
insert into results values(12,'myhrer','bronze');
insert into results values(13,'mancuso','silver');
insert into results values(13,'riesch','gold');
insert into results values(13,'paerson','bronze');
insert into results values(15,'ammann','gold');
insert into results values(15,'malysz','silver');
insert into results values(15,'schlierenzauer','bronze');
insert into results values(16,'kuzmina','gold');
insert into results values(16,'neuner','silver');
insert into results values(16,'dorin','bronze');insert into athletes values('svendsen','norway','M');
insert into athletes values('zurbriggen','switzerland','M');
insert into athletes values('jay','france','M');
insert into athletes values('kostelic','croatia','M');
insert into athletes values('myhrer','sweden','M');
insert into athletes values('fak','croatia','M');
insert into athletes values('cleski','usa','M');
insert into athletes values('mo','korea','M');
insert into athletes values('ammann','switzerland','M');
insert into athletes values('malysz','poland','M');
insert into athletes values('schlierenzauer','austria','M');
insert into athletes values('kramer','netherlands','M');
insert into athletes values('skobrev','russia','M');
insert into athletes values('lee','korea','M');
insert into athletes values('kuzmina','slovakia','F');
insert into athletes values('neuner','germany','F');
insert into athletes values('dorin','france','F');
insert into athletes values('davis','usa','M');
insert into athletes values('ohno','usa','M');
insert into athletes values('hedrick','usa','M');
insert into athletes values('kim','korea','F');
insert into athletes values('asada','japan','F');
insert into athletes values('rochette','canada','F');
insert into athletes values('mcivor','canada','F');
insert into athletes values('hedda','norway','F');
insert into athletes values('huttary','austria','F');
insert into athletes values('miller','usa','M');
insert into athletes values('andrea','austria','F');
insert into athletes values('lysacek','usa','M');
insert into athletes values('plushenko','russia','M');
insert into athletes values('takahashi','japan','M');
insert into athletes values('paerson','sweden','F');
insert into athletes values('riesch','germany','F');
insert into athletes values('razzoli','italy','M');
insert into athletes values('mancuso','usa','F');
insert into competitions values(3,'biathlon','1000');
insert into competitions values(4,'skijumping','nh');
insert into competitions values(5,'speedskating','1000');
insert into competitions values(6,'speedskating','500');
insert into competitions values(7,'shorttrack','1500');
insert into competitions values(9,'figureskating','');
insert into competitions values(10,'giantslalom','');
insert into competitions values(11,'crosscountry','');
insert into competitions values(12,'slalom','');
insert into competitions values(13,'super-combined','');
insert into competitions values(15,'skijumping','lh');
insert into competitions values(16,'biathlon','7500');
update text set question='Question is: did mancuso win silver in super-combined?',sql='Corresponding SQL generated is: select count(*) from results r ,competitions c where r.comp_id=c.comp_id and r.medal="silver" and c.name="super-combined" and r.winner="mancuso";' where number=1;
select question from text where number =1;
select sql from text where number =1;
select sentence from text where number =1;
select count(*) from results r ,competitions c where r.comp_id=c.comp_id and r.medal="silver" and c.name="super-combined" and r.winner="mancuso";
select separator from text where number =1;
update text set question='Question is: did razzoli arrive first in giantslalom?',sql='Corresponding SQL generated is: select count(*) from results r ,competitions c where r.comp_id=c.comp_id and r.medal="gold" and c.name="giantslalom" and r.winner="razzoli";' where number=2;
select question from text where number =2;
select sql from text where number =2;
select sentence from text where number =2;
select count(*) from results r ,competitions c where r.comp_id=c.comp_id and r.medal="gold" and c.name="giantslalom" and r.winner="razzoli";
select separator from text where number =2;
update text set question='Question is: did a slovakian woman win gold in biathlon?',sql='Corresponding SQL generated is: select count(*) from athletes a,results r ,competitions c where r.winner=a.name and r.comp_id=c.comp_id and r.medal="gold" and c.name="biathlon" and a.gender="F" and a.nationality="slovakia";' where number=3;
select question from text where number =3;
select sql from text where number =3;
select sentence from text where number =3;
select count(*) from athletes a,results r ,competitions c where r.winner=a.name and r.comp_id=c.comp_id and r.medal="gold" and c.name="biathlon" and a.gender="F" and a.nationality="slovakia";
select separator from text where number =3;
update text set question='Question is: did a swiss woman arrive first in skijumping?',sql='Corresponding SQL generated is: select count(*) from athletes a,results r ,competitions c where r.winner=a.name and r.comp_id=c.comp_id and r.medal="gold" and c.name="skijumping" and a.gender="F" and a.nationality="switzerland";' where number=4;
select question from text where number =4;
select sql from text where number =4;
select sentence from text where number =4;
select count(*) from athletes a,results r ,competitions c where r.winner=a.name and r.comp_id=c.comp_id and r.medal="gold" and c.name="skijumping" and a.gender="F" and a.nationality="switzerland";
select separator from text where number =4;
update text set question='Question is: Who won silver in shorttrack?',sql='Corresponding SQL generated is: select r.winner from results r ,competitions c where r.comp_id=c.comp_id and r.medal="silver" and c.name="shorttrack";' where number=5;
select question from text where number =5;
select sql from text where number =5;
select sentence from text where number =5;
select r.winner from results r ,competitions c where r.comp_id=c.comp_id and r.medal="silver" and c.name="shorttrack";
select separator from text where number =5;
update text set question='Question is: who arrive third in crosscountry?',sql='Corresponding SQL generated is: select r.winner from results r ,competitions c where r.comp_id=c.comp_id and r.medal="bronze" and c.name="crosscountry";' where number=6;
select question from text where number =6;
select sql from text where number =6;
select sentence from text where number =6;
select r.winner from results r ,competitions c where r.comp_id=c.comp_id and r.medal="bronze" and c.name="crosscountry";
select separator from text where number =6;
.exit;